Repository DevTraces/BackEnd, pull requests merged in 2023-03, with the labels that each got.

#135 비밀번호 수정을 위한 이메일 인증, 인증키 확인, 새 비밀번호 설정 API 구현
  src/main/java/com/devtraces/arterest/common/exception/BaseException.java
  src/main/java/com/devtraces/arterest/common/exception/ErrorCode.java
  src/main/java/com/devtraces/arterest/configuration/SecurityConfiguration.java
  src/main/java/com/devtraces/arterest/controller/user/UserController.java
  src/main/java/com/devtraces/arterest/controller/user/dto/request/CheckAuthkeyForNewPasswordRequest.java
  src/main/java/com/devtraces/arterest/controller/user/dto/request/ResetPasswordRequest.java
  src/main/java/com/devtraces/arterest/controller/user/dto/request/SendMailWithAuthkeyForNewPasswordRequest.java
  src/main/java/com/devtraces/arterest/controller/user/dto/response/CheckAuthkeyForNewPasswordResponse.java
  src/main/java/com/devtraces/arterest/controller/user/dto/response/ResetPasswordResponse.java
  src/main/java/com/devtraces/arterest/service/auth/AuthService.java
  src/main/java/com/devtraces/arterest/service/user/RedisService.java
  src/main/java/com/devtraces/arterest/service/user/UserService.java
  src/test/java/com/devtraces/arterest/service/user/UserServiceTest.java
Labels: ☑️test, ✨feature

#137 회원탈퇴 로직 수정
  src/main/java/com/devtraces/arterest/controller/auth/AuthController.java
  src/main/java/com/devtraces/arterest/controller/auth/dto/request/DeleteUserRequest.java
  src/main/java/com/devtraces/arterest/service/auth/AuthService.java
  src/test/java/com/devtraces/arterest/service/user/AuthServiceTest.java
Labels: 🐞bugFix

#138 회원탈퇴 API 수정
  src/main/java/com/devtraces/arterest/model/bookmark/BookmarkRepository.java
  src/main/java/com/devtraces/arterest/model/like/LikeRepository.java
  src/main/java/com/devtraces/arterest/service/auth/AuthService.java
  src/test/java/com/devtraces/arterest/service/user/AuthServiceTest.java
Labels: 🐞bugFix

#140 Async 어노테이션 적용
  src/main/java/com/devtraces/arterest/ArterestApplication.java
  src/main/java/com/devtraces/arterest/common/constant/CommonConstant.java
  src/main/java/com/devtraces/arterest/configuration/async/CustomAsyncExceptionHandler.java
  src/main/java/com/devtraces/arterest/configuration/async/ThreadPoolConfig.java
  src/main/java/com/devtraces/arterest/service/follow/FollowService.java
  src/main/java/com/devtraces/arterest/service/like/LikeService.java
  src/main/java/com/devtraces/arterest/service/reply/ReplyService.java
  src/main/java/com/devtraces/arterest/service/rereply/RereplyService.java
Labels: ✨feature

#144 이미지 파일 확장자 추가 & 팔로우 추천 리스트 로직 수정
  src/main/java/com/devtraces/arterest/controller/follow/FollowController.java
  src/main/java/com/devtraces/arterest/model/follow/FollowRepository.java
  src/main/java/com/devtraces/arterest/service/follow/FollowService.java
  src/main/java/com/devtraces/arterest/service/s3/S3Service.java
  src/test/java/com/devtraces/arterest/service/follow/FollowServiceTest.java
Labels: 🐞bugFix, ✨feature

#145 카카오 로그인시 랜덤 닉네임 변경
  src/main/java/com/devtraces/arterest/common/constant/CommonConstant.java
  src/main/java/com/devtraces/arterest/service/auth/OauthService.java
Labels: ☑️test, ✨feature

#148 이메일 인증코드 확인 및 회원가입시 인증여부 확인 로직 추가
  src/main/java/com/devtraces/arterest/controller/auth/AuthController.java
  src/main/java/com/devtraces/arterest/controller/auth/dto/response/MailAuthKeyCheckResponse.java
  src/main/java/com/devtraces/arterest/controller/auth/dto/response/UserRegistrationResponse.java
  src/main/java/com/devtraces/arterest/service/auth/AuthService.java
  src/test/java/com/devtraces/arterest/service/user/AuthServiceTest.java
Labels: ☑️test, ✨feature

#150 해시태그 공백 및 중복 제거
  src/main/java/com/devtraces/arterest/service/feed/FeedService.java
Labels: 🐞bugFix

#151 쿼리 성능 최적화 - 게시물, 댓글, 대댓글 리스트 관련 N+1 문제 해결
  src/main/java/com/devtraces/arterest/controller/feed/dto/response/FeedResponse.java
  src/main/java/com/devtraces/arterest/controller/feed/dto/response/FeedResponseConverter.java
  src/main/java/com/devtraces/arterest/controller/reply/dto/response/ReplyResponse.java
  src/main/java/com/devtraces/arterest/controller/reply/dto/response/ReplyResponseConverter.java
  src/main/java/com/devtraces/arterest/controller/rereply/dto/response/RereplyResponse.java
  src/main/java/com/devtraces/arterest/controller/rereply/dto/response/RereplyResponseConverter.java
  src/main/java/com/devtraces/arterest/model/feed/Feed.java
  src/main/java/com/devtraces/arterest/model/feed/FeedRepository.java
  src/main/java/com/devtraces/arterest/model/reply/Reply.java
  src/main/java/com/devtraces/arterest/model/reply/ReplyRepository.java
  src/main/java/com/devtraces/arterest/model/rereply/RereplyRepository.java
  src/main/java/com/devtraces/arterest/service/auth/AuthService.java
  src/main/java/com/devtraces/arterest/service/feed/FeedReadService.java
  src/main/java/com/devtraces/arterest/service/feed/FeedService.java
  src/main/java/com/devtraces/arterest/service/follow/FollowService.java
  src/main/java/com/devtraces/arterest/service/reply/ReplyService.java
  src/main/java/com/devtraces/arterest/service/rereply/RereplyService.java
  src/test/http/test.http
  src/test/java/com/devtraces/arterest/service/feed/FeedReadServiceTest.java
  src/test/java/com/devtraces/arterest/service/feed/dto/FeedResponseConverterImpl.java
  src/test/java/com/devtraces/arterest/service/follow/FollowServiceTest.java
  src/test/java/com/devtraces/arterest/service/reply/ReplyResponseConverterImpl.java
  src/test/java/com/devtraces/arterest/service/reply/ReplyServiceTest.java
  src/test/java/com/devtraces/arterest/service/rereply/RereplyResponseConverterImpl.java
  src/test/java/com/devtraces/arterest/service/rereply/RereplyServiceTest.java
Labels: ✨feature, 🔨refactor

#153 추천 로직에서 사용하는 스레드 개수 4 -> 2로 절감
  src/main/java/com/devtraces/arterest/service/feed/FeedSamplingService.java
  src/main/java/com/devtraces/arterest/service/follow/FollowService.java
  src/main/java/com/devtraces/arterest/service/recommendation/initializing/RecommendationListInitializationService.java
  src/main/java/com/devtraces/arterest/service/recommendation/sampling/FollowAndLikeInfoSamplingService.java
  src/test/java/com/devtraces/arterest/service/feed/FeedSamplingServiceTest.java
  src/test/java/com/devtraces/arterest/service/follow/FollowServiceTest.java
  src/test/java/com/devtraces/arterest/service/recommendation/initializing/RecommendationListInitializationServiceTest.java
  src/test/java/com/devtraces/arterest/service/recommendation/sampling/FollowAndLikeInfoSamplingServiceTest.java
Labels: 🐞bugFix, 🔨refactor

#155 피드/댓글/대댓글 삭제시 관련 알림도 삭제하는 기능 구현
  src/main/java/com/devtraces/arterest/model/notice/NoticeRepository.java
  src/main/java/com/devtraces/arterest/service/feed/application/FeedDeleteApplication.java
  src/main/java/com/devtraces/arterest/service/notice/NoticeService.java
  src/main/java/com/devtraces/arterest/service/reply/ReplyService.java
  src/main/java/com/devtraces/arterest/service/rereply/RereplyService.java
  src/test/java/com/devtraces/arterest/service/feed/application/FeedDeleteApplicationTest.java
  src/test/java/com/devtraces/arterest/service/notice/NoticeServiceTest.java
  src/test/java/com/devtraces/arterest/service/reply/ReplyServiceTest.java
  src/test/java/com/devtraces/arterest/service/rereply/RereplyServiceTest.java
Labels: ☑️test, ✨feature

#157 Async 어노테이션 적용 적용 위치 변경
  src/main/java/com/devtraces/arterest/service/feed/application/FeedDeleteApplication.java
  src/main/java/com/devtraces/arterest/service/reply/ReplyService.java
  src/main/java/com/devtraces/arterest/service/rereply/RereplyService.java
Labels: 🐞bugFix

#158 사용자 탈퇴시 관련 알림 삭제 기능 구현
  src/main/java/com/devtraces/arterest/service/auth/AuthService.java
  src/main/java/com/devtraces/arterest/service/notice/NoticeService.java
  src/main/java/com/devtraces/arterest/service/reply/ReplyService.java
  src/main/java/com/devtraces/arterest/service/rereply/RereplyService.java
  src/test/java/com/devtraces/arterest/service/notice/NoticeServiceTest.java
  src/test/java/com/devtraces/arterest/service/user/AuthServiceTest.java
Labels: ☑️test, ✨feature

#162 카카오 로그인시 kakaoUserId로 사용자 식별하는 로직으로 수정
  src/main/java/com/devtraces/arterest/service/auth/OauthService.java
  src/test/java/com/devtraces/arterest/service/auth/OauthServiceTest.java
Labels: 🐞bugFix

#163 게시물 생성/수정 시 해시태그 관련 오류 해결
  src/main/java/com/devtraces/arterest/service/feed/FeedService.java
Labels: 🐞bugFix

#169 회원탈퇴시 JWT 쿠키 제거 로직 추가
  src/main/java/com/devtraces/arterest/common/jwt/JwtProvider.java
  src/main/java/com/devtraces/arterest/controller/auth/AuthController.java
Labels: 🐞bugFix
