Repository DevTraces/BackEnd, pull requests merged in 2023-02, with the labels that each got.

#4 유저, 피드, 댓글, 대댓글 엔티티 구현
  build.gradle
  src/main/java/com/devtraces/arterest/common/UserSignUpType.java
  src/main/java/com/devtraces/arterest/common/UserStatusType.java
  src/main/java/com/devtraces/arterest/common/domain/BaseEntity.java
  src/main/java/com/devtraces/arterest/configuration/JpaAuditingConfiguration.java
  src/main/java/com/devtraces/arterest/domain/feed/Feed.java
  src/main/java/com/devtraces/arterest/domain/feed/FeedRepository.java
  src/main/java/com/devtraces/arterest/domain/reply/Reply.java
  src/main/java/com/devtraces/arterest/domain/reply/ReplyRepository.java
  src/main/java/com/devtraces/arterest/domain/rereply/Rereply.java
  src/main/java/com/devtraces/arterest/domain/rereply/RereplyRepository.java
  src/main/java/com/devtraces/arterest/domain/user/User.java
  src/main/java/com/devtraces/arterest/domain/user/UserRepository.java
  src/main/resources/application.yml
  src/test/http/test.http
Labels: ✨feature

#9 CI/CD를 위한 환경 구축 및 파일 설정
  .github/workflows/deploy.yaml
  appspec.yml
  scripts/start.sh
  scripts/stop.sh
Labels: 🌎deploy

#10 북마크 엔티티, API 구현, 테스트 코드 작성
  src/main/java/com/devtraces/arterest/common/exception/ErrorCode.java
  src/main/java/com/devtraces/arterest/controller/BookmarkController.java
  src/main/java/com/devtraces/arterest/domain/bookmark/Bookmark.java
  src/main/java/com/devtraces/arterest/domain/bookmark/BookmarkRepository.java
  src/main/java/com/devtraces/arterest/domain/feed/Feed.java
  src/main/java/com/devtraces/arterest/domain/user/User.java
  src/main/java/com/devtraces/arterest/domain/user/UserRepository.java
  src/main/java/com/devtraces/arterest/dto/GetBookmarkListResponse.java
  src/main/java/com/devtraces/arterest/service/BookmarkService.java
  src/test/java/com/devtraces/arterest/controller/BookmarkControllerTest.java
  src/test/java/com/devtraces/arterest/service/BookmarkServiceTest.java
Labels: ☑️test, ✨feature

#13 JWT 로그인, 로그아웃, 토큰 재발급 API 구현
  .gitignore
  build.gradle
  src/main/java/com/devtraces/arterest/common/exception/BaseException.java
  src/main/java/com/devtraces/arterest/common/exception/ErrorCode.java
  src/main/java/com/devtraces/arterest/common/exception/ErrorController.java
  src/main/java/com/devtraces/arterest/common/jwt/JwtAuthenticationEntryPoint.java
  src/main/java/com/devtraces/arterest/common/jwt/JwtAuthenticationFilter.java
  src/main/java/com/devtraces/arterest/common/jwt/JwtProperties.java
  src/main/java/com/devtraces/arterest/common/jwt/JwtProvider.java
  src/main/java/com/devtraces/arterest/common/jwt/controller/JwtController.java
  src/main/java/com/devtraces/arterest/common/jwt/dto/ReissueRequest.java
  src/main/java/com/devtraces/arterest/common/jwt/dto/TokenDto.java
  src/main/java/com/devtraces/arterest/common/jwt/service/JwtService.java
  src/main/java/com/devtraces/arterest/common/redis/service/RedisService.java
  src/main/java/com/devtraces/arterest/common/response/ApiErrorResponse.java
  src/main/java/com/devtraces/arterest/common/security/SecurityUser.java
  src/main/java/com/devtraces/arterest/common/security/SecurityUserDetailService.java
  src/main/java/com/devtraces/arterest/configuration/EncodingConfiguration.java
  src/main/java/com/devtraces/arterest/configuration/RedisConfiguration.java
  src/main/java/com/devtraces/arterest/configuration/SecurityConfiguration.java
  src/main/java/com/devtraces/arterest/controller/user/AuthController.java
  src/main/java/com/devtraces/arterest/controller/user/dto/SignInRequest.java
  src/main/java/com/devtraces/arterest/domain/user/UserRepository.java
  src/main/java/com/devtraces/arterest/service/user/AuthService.java
  src/test/java/com/devtraces/arterest/common/jwt/JwtProviderTest.java
  src/test/java/com/devtraces/arterest/common/jwt/service/JwtServiceTest.java
  src/test/java/com/devtraces/arterest/service/user/AuthServiceTest.java
Labels: ☑️test, ✨feature

#17 fix: 북마크 엔티티 중복 칼럼 제거, 관련 로직 수정 (#6)
  src/main/java/com/devtraces/arterest/common/exception/ErrorCode.java
  src/main/java/com/devtraces/arterest/controller/bookmark/BookmarkController.java
  src/main/java/com/devtraces/arterest/controller/bookmark/dto/GetBookmarkListResponse.java
  src/main/java/com/devtraces/arterest/domain/bookmark/Bookmark.java
  src/main/java/com/devtraces/arterest/service/bookmark/BookmarkService.java
  src/test/java/com/devtraces/arterest/controller/BookmarkControllerTest.java
  src/test/java/com/devtraces/arterest/service/BookmarkServiceTest.java
Labels: 🐞bugFix

#15 S3 파일 업로더 구현
  build.gradle
  src/main/java/com/devtraces/arterest/common/component/S3Uploader.java
  src/main/java/com/devtraces/arterest/common/exception/BaseException.java
  src/main/java/com/devtraces/arterest/common/exception/ErrorCode.java
  src/main/java/com/devtraces/arterest/configuration/AwsS3Configuration.java
Labels: ✨feature

#11 피드 1개 읽기, 피드 리스트 읽기, 피드 1개 삭제 구현
  src/main/java/com/devtraces/arterest/controller/FeedController.java
  src/main/java/com/devtraces/arterest/domain/feed/FeedRepository.java
  src/main/java/com/devtraces/arterest/domain/like/LikeRepository.java
  src/main/java/com/devtraces/arterest/domain/like/Likes.java
  src/main/java/com/devtraces/arterest/domain/reply/ReplyRepository.java
  src/main/java/com/devtraces/arterest/domain/rereply/RereplyRepository.java
  src/main/java/com/devtraces/arterest/dto/feed/FeedResponse.java
  src/main/java/com/devtraces/arterest/service/FeedService.java
  src/test/http/test.http
  src/test/java/com/devtraces/arterest/service/FeedServiceTest.java
Labels: ✨feature

#19 댓글 및 대댓글 CRUD 구현
  .DS_Store
  src/.DS_Store
  src/main/.DS_Store
  src/main/java/.DS_Store
  src/main/java/com/.DS_Store
  src/main/java/com/devtraces/.DS_Store
  src/main/java/com/devtraces/arterest/.DS_Store
  src/main/java/com/devtraces/arterest/common/.DS_Store
  src/main/java/com/devtraces/arterest/common/CommonUtils.java
  src/main/java/com/devtraces/arterest/common/exception/BaseException.java
  src/main/java/com/devtraces/arterest/common/exception/ErrorCode.java
  src/main/java/com/devtraces/arterest/controller/FeedController.java
  src/main/java/com/devtraces/arterest/controller/reply/ReplyController.java
  src/main/java/com/devtraces/arterest/controller/reply/dto/ReplyRequest.java
  src/main/java/com/devtraces/arterest/controller/reply/dto/ReplyResponse.java
  src/main/java/com/devtraces/arterest/controller/rereply/RereplyController.java
  src/main/java/com/devtraces/arterest/controller/rereply/dto/RereplyRequest.java
  src/main/java/com/devtraces/arterest/controller/rereply/dto/RereplyResponse.java
  src/main/java/com/devtraces/arterest/domain/reply/Reply.java
  src/main/java/com/devtraces/arterest/domain/reply/ReplyRepository.java
  src/main/java/com/devtraces/arterest/domain/rereply/Rereply.java
  src/main/java/com/devtraces/arterest/domain/rereply/RereplyRepository.java
  src/main/java/com/devtraces/arterest/dto/.DS_Store
  src/main/java/com/devtraces/arterest/dto/feed/FeedResponse.java
  src/main/java/com/devtraces/arterest/service/FeedService.java
  src/main/java/com/devtraces/arterest/service/reply/ReplyService.java
  src/main/java/com/devtraces/arterest/service/rereply/RereplyService.java
  src/test/http/test.http
  src/test/java/com/devtraces/arterest/service/FeedServiceTest.java
  src/test/java/com/devtraces/arterest/service/ReplyServiceTest.java
  src/test/java/com/devtraces/arterest/service/RereplyServiceTest.java
Labels: ☑️test, ✨feature

#22 이메일 인증 API 구현
  build.gradle
  src/main/java/com/devtraces/arterest/common/component/MailUtil.java
  src/main/java/com/devtraces/arterest/common/exception/BaseException.java
  src/main/java/com/devtraces/arterest/common/exception/ErrorCode.java
  src/main/java/com/devtraces/arterest/common/redis/service/RedisService.java
  src/main/java/com/devtraces/arterest/controller/user/AuthController.java
  src/main/java/com/devtraces/arterest/controller/user/dto/MailAuthKeyCheckRequest.java
  src/main/java/com/devtraces/arterest/controller/user/dto/MailAuthKeyCheckResponse.java
  src/main/java/com/devtraces/arterest/controller/user/dto/MailAuthKeyRequest.java
  src/main/java/com/devtraces/arterest/domain/user/UserRepository.java
  src/main/java/com/devtraces/arterest/service/user/AuthService.java
  src/test/java/com/devtraces/arterest/service/user/AuthServiceTest.java
Labels: ☑️test, ✨feature

#32 feat: S3Util에 파일 삭제 기능 추가 (#31)
  src/main/java/com/devtraces/arterest/common/component/S3Util.java
  src/main/java/com/devtraces/arterest/common/exception/BaseException.java
  src/main/java/com/devtraces/arterest/common/exception/ErrorCode.java
Labels: ✨feature

#26 카카오 소셜 로그인 API 구현
  .gitignore
  build.gradle
  src/main/java/com/devtraces/arterest/controller/user/OauthController.java
  src/main/java/com/devtraces/arterest/controller/user/dto/OauthKakaoSignInRequest.java
  src/main/java/com/devtraces/arterest/domain/user/User.java
  src/main/java/com/devtraces/arterest/domain/user/UserRepository.java
  src/main/java/com/devtraces/arterest/service/user/AuthService.java
  src/main/java/com/devtraces/arterest/service/user/OauthService.java
  src/main/java/com/devtraces/arterest/service/user/dto/UserInfoFromKakaoDto.java
Labels: ✨feature

#38 에러 해결위해서 SpringConfiguration에서 CORS 설정 로직 추가
  .github/workflows/deploy.yaml
  src/main/java/com/devtraces/arterest/configuration/SecurityConfiguration.java
Labels: 🐞bugFix

#33 게시물 CRUD API 구현 & 게시물과 해시태그간 N:M 매핑 구현
  .DS_Store
  src/main/java/com/devtraces/arterest/common/CommonUtils.java
  src/main/java/com/devtraces/arterest/common/component/S3Util.java
  src/main/java/com/devtraces/arterest/common/exception/BaseException.java
  src/main/java/com/devtraces/arterest/common/exception/ErrorCode.java
  src/main/java/com/devtraces/arterest/configuration/RedisConfiguration.java
  src/main/java/com/devtraces/arterest/controller/feed/FeedController.java
  src/main/java/com/devtraces/arterest/controller/feed/dto/FeedCreateResponse.java
  src/main/java/com/devtraces/arterest/controller/feed/dto/FeedResponse.java
  src/main/java/com/devtraces/arterest/controller/feed/dto/FeedUpdateResponse.java
  src/main/java/com/devtraces/arterest/controller/reply/dto/ReplyRequest.java
  src/main/java/com/devtraces/arterest/domain/bookmark/BookmarkRepository.java
  src/main/java/com/devtraces/arterest/domain/feed/Feed.java
  src/main/java/com/devtraces/arterest/domain/feed/FeedRepository.java
  src/main/java/com/devtraces/arterest/domain/feedhashtagmap/FeedHashtagMap.java
  src/main/java/com/devtraces/arterest/domain/feedhashtagmap/FeedHashtagMapRepository.java
  src/main/java/com/devtraces/arterest/domain/hashtag/Hashtag.java
  src/main/java/com/devtraces/arterest/domain/hashtag/HashtagRepository.java
  src/main/java/com/devtraces/arterest/domain/like/LikeRepository.java
  src/main/java/com/devtraces/arterest/domain/like/Likes.java
  src/main/java/com/devtraces/arterest/domain/likecache/LikeNumberCacheRepository.java
  src/main/java/com/devtraces/arterest/domain/reply/ReplyRepository.java
  src/main/java/com/devtraces/arterest/domain/rereply/RereplyRepository.java
  src/main/java/com/devtraces/arterest/domain/user/User.java
  src/main/java/com/devtraces/arterest/domain/user/UserRepository.java
  src/main/java/com/devtraces/arterest/dto/.DS_Store
  src/main/java/com/devtraces/arterest/service/feed/FeedService.java
  src/main/java/com/devtraces/arterest/service/reply/ReplyService.java
  src/main/java/com/devtraces/arterest/service/rereply/RereplyService.java
  src/test/http/test.http
  src/test/java/com/devtraces/arterest/service/feed/FeedServiceTest.java
  src/test/java/com/devtraces/arterest/service/reply/ReplyServiceTest.java
  src/test/java/com/devtraces/arterest/service/rereply/RereplyServiceTest.java
Labels: ☑️test, ✨feature

#20 검색어 자동완성 API 구현
  .DS_Store
  .gitignore
  build.gradle
  src/.DS_Store
  src/main/.DS_Store
  src/main/java/.DS_Store
  src/main/java/com/.DS_Store
  src/main/java/com/devtraces/.DS_Store
  src/main/java/com/devtraces/arterest/.DS_Store
  src/main/java/com/devtraces/arterest/ArterestApplication.java
  src/main/java/com/devtraces/arterest/common/.DS_Store
  src/main/java/com/devtraces/arterest/common/exception/BaseException.java
  src/main/java/com/devtraces/arterest/common/exception/ErrorCode.java
  src/main/java/com/devtraces/arterest/common/redis/service/RedisService.java
  src/main/java/com/devtraces/arterest/configuration/TrieConfiguration.java
  src/main/java/com/devtraces/arterest/controller/search/SearchController.java
  src/main/java/com/devtraces/arterest/domain/feedhashtagmap/FeedHashtagMap.java
  src/main/java/com/devtraces/arterest/domain/feedhashtagmap/FeedHashtagMapRepository.java
  src/main/java/com/devtraces/arterest/domain/hashtag/HashtagRepository.java
  src/main/java/com/devtraces/arterest/service/bookmark/BookmarkService.java
  src/main/java/com/devtraces/arterest/service/search/SearchService.java
  src/test/http/test.http
  src/test/java/com/devtraces/arterest/service/BookmarkServiceTest.java
  src/test/java/com/devtraces/arterest/service/search/SearchServiceTest.java
Labels: ☑️test, ✨feature

#45 CI/CD 를 위한 deploy 및 실행 스크립트 작성
  .github/workflows/deploy.yaml
  scripts/start.sh
  scripts/stop.sh
  src/main/resources/application.yml
Labels: 🌎deploy

#30 회원가입 API
  src/main/java/com/devtraces/arterest/common/exception/BaseException.java
  src/main/java/com/devtraces/arterest/common/exception/ErrorCode.java
  src/main/java/com/devtraces/arterest/common/redis/service/RedisService.java
  src/main/java/com/devtraces/arterest/controller/user/AuthController.java
  src/main/java/com/devtraces/arterest/controller/user/dto/UserRegistrationRequest.java
  src/main/java/com/devtraces/arterest/controller/user/dto/UserRegistrationResponse.java
  src/main/java/com/devtraces/arterest/domain/user/UserRepository.java
  src/main/java/com/devtraces/arterest/service/user/AuthService.java
  src/main/resources/application.yml
  src/test/java/com/devtraces/arterest/service/user/AuthServiceTest.java
Labels: ☑️test, ✨feature

#36 해시태그, 이름, 닉네임 검색 API 구현
  .gitignore
  src/main/java/com/devtraces/arterest/common/exception/BaseException.java
  src/main/java/com/devtraces/arterest/controller/search/SearchController.java
  src/main/java/com/devtraces/arterest/controller/search/dto/GetHashtagsSearchResponse.java
  src/main/java/com/devtraces/arterest/controller/search/dto/GetNicknameSearchResponse.java
  src/main/java/com/devtraces/arterest/controller/search/dto/GetUsernameSearchResponse.java
  src/main/java/com/devtraces/arterest/domain/hashtag/Hashtag.java
  src/main/java/com/devtraces/arterest/domain/hashtag/HashtagRepository.java
  src/main/java/com/devtraces/arterest/domain/user/User.java
  src/main/java/com/devtraces/arterest/domain/user/UserRepository.java
  src/main/java/com/devtraces/arterest/service/search/SearchService.java
  src/test/java/com/devtraces/arterest/service/search/SearchServiceTest.java
Labels: ☑️test, ✨feature

#49 Access token 및 Refresh token 전송 방식 변경
  src/main/java/com/devtraces/arterest/common/jwt/JwtProvider.java
  src/main/java/com/devtraces/arterest/common/jwt/controller/JwtController.java
  src/main/java/com/devtraces/arterest/common/jwt/dto/ReissueRequest.java
  src/main/java/com/devtraces/arterest/common/jwt/dto/TokenDto.java
  src/main/java/com/devtraces/arterest/controller/user/AuthController.java
  src/main/java/com/devtraces/arterest/controller/user/OauthController.java
Labels: ✨feature

#42 이메일/닉네임 중복, 비밀번호 변경 API 구현
  src/main/java/com/devtraces/arterest/common/exception/BaseException.java
  src/main/java/com/devtraces/arterest/common/exception/ErrorCode.java
  src/main/java/com/devtraces/arterest/controller/user/UserController.java
  src/main/java/com/devtraces/arterest/controller/user/dto/EmailCheckRequest.java
  src/main/java/com/devtraces/arterest/controller/user/dto/EmailCheckResponse.java
  src/main/java/com/devtraces/arterest/controller/user/dto/NicknameCheckRequest.java
  src/main/java/com/devtraces/arterest/controller/user/dto/NicknameCheckResponse.java
  src/main/java/com/devtraces/arterest/controller/user/dto/PasswordUpdateRequest.java
  src/main/java/com/devtraces/arterest/domain/user/User.java
  src/main/java/com/devtraces/arterest/service/user/UserService.java
  src/test/java/com/devtraces/arterest/service/user/UserServiceTest.java
Labels: ☑️test, ✨feature

#44 팔로우 관계 CRUD API 구현
  src/main/java/com/devtraces/arterest/common/CommonUtils.java
  src/main/java/com/devtraces/arterest/common/exception/BaseException.java
  src/main/java/com/devtraces/arterest/common/exception/ErrorCode.java
  src/main/java/com/devtraces/arterest/controller/follow/FollowController.java
  src/main/java/com/devtraces/arterest/controller/follow/dto/FollowResponse.java
  src/main/java/com/devtraces/arterest/domain/follow/Follow.java
  src/main/java/com/devtraces/arterest/domain/follow/FollowRepository.java
  src/main/java/com/devtraces/arterest/domain/user/User.java
  src/main/java/com/devtraces/arterest/domain/user/UserRepository.java
  src/main/java/com/devtraces/arterest/service/follow/FollowService.java
  src/test/http/test.http
  src/test/java/com/devtraces/arterest/service/follow/FollowServiceTest.java
Labels: ✨feature

#54 accessToken에서 accessTokenFromKakao로 필드명 변경
  src/main/java/com/devtraces/arterest/controller/user/OauthController.java
  src/main/java/com/devtraces/arterest/controller/user/dto/OauthKakaoSignInRequest.java
  src/main/java/com/devtraces/arterest/service/user/OauthService.java
Labels: 🐞bugFix

#51 사용자 프로필 조회/수정 API 구현
  .gitignore
  src/main/java/com/devtraces/arterest/controller/user/UserController.java
  src/main/java/com/devtraces/arterest/controller/user/dto/ProfileByNicknameResponse.java
  src/main/java/com/devtraces/arterest/controller/user/dto/UpdateProfileResponse.java
  src/main/java/com/devtraces/arterest/domain/feed/FeedRepository.java
  src/main/java/com/devtraces/arterest/domain/user/User.java
  src/main/java/com/devtraces/arterest/service/user/UserService.java
  src/test/java/com/devtraces/arterest/common/jwt/JwtProviderTest.java
  src/test/java/com/devtraces/arterest/common/jwt/service/JwtServiceTest.java
  src/test/java/com/devtraces/arterest/service/user/AuthServiceTest.java
  src/test/java/com/devtraces/arterest/service/user/UserServiceTest.java
Labels: ☑️test, ✨feature

#50 게시물 수정 시, 이미지 처리하는 방식 수정
  src/main/java/com/devtraces/arterest/controller/feed/FeedController.java
  src/main/java/com/devtraces/arterest/controller/feed/dto/create/FeedCreateResponse.java
  src/main/java/com/devtraces/arterest/controller/feed/dto/update/ExistingImageUrlDto.java
  src/main/java/com/devtraces/arterest/controller/feed/dto/update/FeedUpdateRequest.java
  src/main/java/com/devtraces/arterest/controller/feed/dto/update/FeedUpdateResponse.java
  src/main/java/com/devtraces/arterest/service/feed/FeedService.java
  src/test/http/test.http
  src/test/java/com/devtraces/arterest/service/feed/FeedServiceTest.java
Labels: ✨feature

#59 User 클래스의 필드 수정 함수 update()에서 set()으로 변경
  src/main/java/com/devtraces/arterest/domain/user/User.java
  src/main/java/com/devtraces/arterest/service/user/UserService.java
Labels: 🐞bugFix

#57 JWT 재발급 및 JWT 관련 에러 메시지 리턴 로직 수정
  src/main/java/com/devtraces/arterest/common/jwt/JwtAccessDeniedHandler.java
  src/main/java/com/devtraces/arterest/common/jwt/JwtProvider.java
  src/main/java/com/devtraces/arterest/common/jwt/controller/JwtController.java
  src/main/java/com/devtraces/arterest/common/jwt/service/JwtService.java
  src/main/java/com/devtraces/arterest/configuration/SecurityConfiguration.java
  src/test/java/com/devtraces/arterest/common/jwt/JwtProviderTest.java
  src/test/java/com/devtraces/arterest/common/jwt/service/JwtServiceTest.java
  src/test/java/com/devtraces/arterest/service/user/AuthServiceTest.java
Labels: 🐞bugFix

#66 카카오 소셜로그인시 username을 nickname과 같게 수정
  src/main/java/com/devtraces/arterest/service/user/OauthService.java
Labels: 🐞bugFix

#67 로그인시 Access Token 인증을 하지 않게 로직 수정
  src/main/java/com/devtraces/arterest/configuration/SecurityConfiguration.java
Labels: 🐞bugFix

#68 게시물 수정 메서드 입력 파라미터 변경 리팩토링
  src/main/java/com/devtraces/arterest/controller/feed/FeedController.java
  src/main/java/com/devtraces/arterest/controller/feed/dto/ExistingImageUrlDto.java
  src/main/java/com/devtraces/arterest/controller/feed/dto/request/FeedUpdateRequest.java
  src/main/java/com/devtraces/arterest/controller/feed/dto/response/FeedUpdateResponse.java
  src/main/java/com/devtraces/arterest/service/feed/FeedService.java
  src/test/java/com/devtraces/arterest/service/feed/FeedServiceTest.java
Labels: 🔨refactor

#75 검색 및 북마크 관련 에러 수정
  src/main/java/com/devtraces/arterest/model/bookmark/Bookmark.java
  src/main/java/com/devtraces/arterest/model/feedhashtagmap/FeedHashtagMap.java
  src/main/java/com/devtraces/arterest/model/feedhashtagmap/FeedHashtagMapRepository.java
  src/main/java/com/devtraces/arterest/model/hashtag/Hashtag.java
  src/main/java/com/devtraces/arterest/model/like/Likes.java
  src/main/java/com/devtraces/arterest/model/user/UserRepository.java
  src/main/java/com/devtraces/arterest/service/bookmark/BookmarkService.java
  src/main/java/com/devtraces/arterest/service/feed/FeedDeleteService.java
  src/main/java/com/devtraces/arterest/service/search/SearchService.java
  src/test/java/com/devtraces/arterest/service/bookmark/BookmarkServiceTest.java
  src/test/java/com/devtraces/arterest/service/feed/FeedServiceTest.java
  src/test/java/com/devtraces/arterest/service/search/SearchServiceTest.java
Labels: 🐞bugFix

#77 소셜로그인으로 중복 회원가입 시도할 때 예외처리 추가
  src/main/java/com/devtraces/arterest/common/exception/BaseException.java
  src/main/java/com/devtraces/arterest/common/exception/ErrorCode.java
  src/main/java/com/devtraces/arterest/service/auth/OauthService.java
Labels: 🐞bugFix, 🔨refactor

#85 카카오 회원가입한 유저 로그인 가능하게 수정
  src/main/java/com/devtraces/arterest/service/auth/OauthService.java
Labels: 🐞bugFix

#83 swagger 적용
  build.gradle
  src/main/java/com/devtraces/arterest/configuration/SecurityConfiguration.java
  src/main/java/com/devtraces/arterest/configuration/SwaggerConfiguration.java
  src/main/resources/application.yml
Labels: ⚙️settings

#84 JWT 재발급 및 로그아웃 로직 수정
  src/main/java/com/devtraces/arterest/common/exception/ErrorCode.java
  src/main/java/com/devtraces/arterest/common/jwt/JwtProvider.java
  src/main/java/com/devtraces/arterest/common/jwt/controller/JwtController.java
  src/main/java/com/devtraces/arterest/common/jwt/service/JwtService.java
  src/main/java/com/devtraces/arterest/configuration/SecurityConfiguration.java
  src/main/java/com/devtraces/arterest/service/auth/util/TokenRedisUtil.java
Labels: 🐞bugFix

#87 게시물 수정시 해시태그 삭제 로직 추가
  src/main/java/com/devtraces/arterest/service/feed/FeedDeleteService.java
  src/main/java/com/devtraces/arterest/service/feed/FeedService.java
Labels: 🐞bugFix

#79 팔로우 관계 중복 저장 에러 수정
  src/main/java/com/devtraces/arterest/common/exception/BaseException.java
  src/main/java/com/devtraces/arterest/common/exception/ErrorCode.java
  src/main/java/com/devtraces/arterest/model/follow/Follow.java
  src/main/java/com/devtraces/arterest/model/follow/FollowRepository.java
  src/main/java/com/devtraces/arterest/service/follow/FollowService.java
  src/test/java/com/devtraces/arterest/service/follow/FollowServiceTest.java
Labels: 🐞bugFix

#88 프로필 조회시 팔로우 정보 추가
  src/main/java/com/devtraces/arterest/controller/user/UserController.java
  src/main/java/com/devtraces/arterest/controller/user/dto/response/ProfileByNicknameResponse.java
  src/main/java/com/devtraces/arterest/model/follow/FollowRepository.java
  src/main/java/com/devtraces/arterest/service/user/UserService.java
  src/test/java/com/devtraces/arterest/service/user/UserServiceTest.java
Labels: ☑️test, ✨feature

#90 회원가입 시 프로필 이미지 s3에 저장 안되는 문제 해결
  src/main/java/com/devtraces/arterest/controller/auth/AuthController.java
  src/main/java/com/devtraces/arterest/service/auth/AuthService.java
  src/test/java/com/devtraces/arterest/service/user/AuthServiceTest.java
Labels: 🐞bugFix

#92 회원가입 시 description null이어도 요청 수신 가능하게 수정
  src/main/java/com/devtraces/arterest/controller/auth/AuthController.java
Labels: 🐞bugFix

#82 게시물 수정 관련 테스트코드 수정
  src/test/java/com/devtraces/arterest/service/feed/FeedServiceTest.java
Labels: 🐞bugFix

#97 로그인 및 토큰 재발급 시 refresh token 전송방식 변경
  src/main/java/com/devtraces/arterest/common/jwt/JwtProvider.java
  src/main/java/com/devtraces/arterest/common/jwt/controller/JwtController.java
  src/main/java/com/devtraces/arterest/common/jwt/dto/TokenDto.java
  src/main/java/com/devtraces/arterest/controller/auth/AuthController.java
  src/main/java/com/devtraces/arterest/controller/auth/OauthController.java
  src/main/java/com/devtraces/arterest/controller/auth/dto/TokenWithNicknameDto.java
Labels: 🐞bugFix

#93 좋아요 관련 API 구현
  src/main/java/com/devtraces/arterest/common/exception/BaseException.java
  src/main/java/com/devtraces/arterest/common/exception/ErrorCode.java
  src/main/java/com/devtraces/arterest/controller/like/LikeController.java
  src/main/java/com/devtraces/arterest/controller/like/dto/response/LikeResponse.java
  src/main/java/com/devtraces/arterest/model/like/LikeRepository.java
  src/main/java/com/devtraces/arterest/model/likecache/LikeNumberCacheRepository.java
  src/main/java/com/devtraces/arterest/model/user/UserRepository.java
  src/main/java/com/devtraces/arterest/service/like/LikeService.java
  src/test/http/test.http
  src/test/java/com/devtraces/arterest/service/like/LikeServiceTest.java
Labels: ✨feature

#98 카카오 소셜 로그인 랜덤 닉네임 생성 로직 구현
  src/main/java/com/devtraces/arterest/service/auth/OauthService.java
  src/test/java/com/devtraces/arterest/service/auth/OauthServiceTest.java
  src/test/java/com/devtraces/arterest/service/feed/FeedServiceTest.java
Labels: 🐞bugFix, 🔨refactor

#96 게시물 관련 API, 댓글 리스트 읽기 관련 API 리팩토링
  src/main/java/com/devtraces/arterest/common/constant/CommonConstant.java
  src/main/java/com/devtraces/arterest/controller/feed/FeedController.java
  src/main/java/com/devtraces/arterest/model/feed/FeedRepository.java
  src/main/java/com/devtraces/arterest/model/reply/ReplyRepository.java
  src/main/java/com/devtraces/arterest/service/feed/FeedReadService.java
  src/main/java/com/devtraces/arterest/service/feed/FeedService.java
  src/main/java/com/devtraces/arterest/service/reply/ReplyService.java
  src/test/java/com/devtraces/arterest/service/feed/FeedReadServiceTest.java
  src/test/java/com/devtraces/arterest/service/feed/FeedServiceTest.java
  src/test/java/com/devtraces/arterest/service/reply/ReplyServiceTest.java
Labels: ✨feature, 🔨refactor

#102 중복 팔로우 및 좋아요에 예외 던지지 않음 & 중복 검사로직 간소화
  src/main/java/com/devtraces/arterest/model/follow/Follow.java
  src/main/java/com/devtraces/arterest/model/like/Likes.java
  src/main/java/com/devtraces/arterest/service/follow/FollowService.java
  src/main/java/com/devtraces/arterest/service/like/LikeService.java
  src/main/java/com/devtraces/arterest/service/reply/ReplyService.java
  src/main/java/com/devtraces/arterest/service/rereply/RereplyService.java
  src/test/java/com/devtraces/arterest/service/follow/FollowServiceTest.java
Labels: 🔨refactor

#106 4가지 알림 저장 기능 구현
  src/main/java/com/devtraces/arterest/common/type/NoticeTarget.java
  src/main/java/com/devtraces/arterest/common/type/NoticeType.java
  src/main/java/com/devtraces/arterest/model/notice/Notice.java
  src/main/java/com/devtraces/arterest/model/notice/NoticeRepository.java
  src/main/java/com/devtraces/arterest/service/notice/NoticeService.java
  src/test/java/com/devtraces/arterest/service/notice/NoticeServiceTest.java
Labels: ☑️test, ✨feature

#111 프로필 정보/이미지 수정 API 구현
  src/main/java/com/devtraces/arterest/controller/user/UserController.java
  src/main/java/com/devtraces/arterest/controller/user/dto/request/UpdateProfileRequest.java
  src/main/java/com/devtraces/arterest/controller/user/dto/response/UpdateProfileImageResponse.java
  src/main/java/com/devtraces/arterest/controller/user/dto/response/UpdateProfileResponse.java
  src/main/java/com/devtraces/arterest/service/user/UserService.java
  src/test/java/com/devtraces/arterest/service/notice/NoticeServiceTest.java
  src/test/java/com/devtraces/arterest/service/user/UserServiceTest.java
Labels: ☑️test, ✨feature

#112 프로필 이미지 삭제 API 구현
  src/main/java/com/devtraces/arterest/controller/user/UserController.java
  src/main/java/com/devtraces/arterest/service/user/UserService.java
  src/test/java/com/devtraces/arterest/service/user/UserServiceTest.java
Labels: ☑️test, ✨feature

#105 게시물 1개 삭제 api 리팩토링
  src/main/java/com/devtraces/arterest/controller/feed/FeedController.java
  src/main/java/com/devtraces/arterest/service/bookmark/BookmarkService.java
  src/main/java/com/devtraces/arterest/service/feed/FeedDeleteService.java
  src/main/java/com/devtraces/arterest/service/feed/FeedReadService.java
  src/main/java/com/devtraces/arterest/service/feed/FeedService.java
  src/main/java/com/devtraces/arterest/service/feed/application/FeedDeleteApplication.java
  src/main/java/com/devtraces/arterest/service/hashtag/HashtagService.java
  src/main/java/com/devtraces/arterest/service/like/LikeService.java
  src/main/java/com/devtraces/arterest/service/reply/ReplyService.java
  src/main/java/com/devtraces/arterest/service/rereply/RereplyService.java
  src/test/java/com/devtraces/arterest/service/bookmark/BookmarkServiceTest.java
  src/test/java/com/devtraces/arterest/service/feed/FeedDeleteServiceTest.java
  src/test/java/com/devtraces/arterest/service/feed/FeedReadServiceTest.java
  src/test/java/com/devtraces/arterest/service/feed/FeedServiceTest.java
  src/test/java/com/devtraces/arterest/service/feed/application/FeedDeleteApplicationTest.java
  src/test/java/com/devtraces/arterest/service/hashtag/HashtagServiceTest.java
  src/test/java/com/devtraces/arterest/service/like/LikeServiceTest.java
  src/test/java/com/devtraces/arterest/service/reply/ReplyServiceTest.java
  src/test/java/com/devtraces/arterest/service/rereply/RereplyServiceTest.java
Labels: 🔨refactor

#108 알림 개수/리스트 조회 API 구현
  src/main/java/com/devtraces/arterest/controller/notice/NoticeController.java
  src/main/java/com/devtraces/arterest/controller/notice/dto/FollowNoticeDto.java
  src/main/java/com/devtraces/arterest/controller/notice/dto/LikeNoticeDto.java
  src/main/java/com/devtraces/arterest/controller/notice/dto/NumberOfNoticeResponse.java
  src/main/java/com/devtraces/arterest/controller/notice/dto/ReplyNoticeDto.java
  src/main/java/com/devtraces/arterest/controller/notice/dto/RereplyNoticeDto.java
  src/main/java/com/devtraces/arterest/controller/notice/dto/response/NoticeListResponse.java
  src/main/java/com/devtraces/arterest/model/notice/Notice.java
  src/main/java/com/devtraces/arterest/model/notice/NoticeRepository.java
  src/main/java/com/devtraces/arterest/service/notice/NoticeService.java
  src/test/java/com/devtraces/arterest/service/notice/NoticeServiceTest.java
Labels: ☑️test, ✨feature

#113 JWT Access Token 발급 방식 변경
  src/main/java/com/devtraces/arterest/common/jwt/JwtAuthenticationFilter.java
  src/main/java/com/devtraces/arterest/common/jwt/JwtProvider.java
  src/main/java/com/devtraces/arterest/common/jwt/controller/JwtController.java
  src/main/java/com/devtraces/arterest/common/jwt/dto/TokenDto.java
  src/main/java/com/devtraces/arterest/common/jwt/service/JwtService.java
  src/main/java/com/devtraces/arterest/controller/auth/AuthController.java
  src/main/java/com/devtraces/arterest/controller/auth/OauthController.java
  src/main/java/com/devtraces/arterest/controller/auth/dto/TokenWithNicknameDto.java
  src/main/java/com/devtraces/arterest/controller/like/LikeController.java
  src/main/java/com/devtraces/arterest/service/like/LikeService.java
  src/test/java/com/devtraces/arterest/common/jwt/JwtProviderTest.java
  src/test/java/com/devtraces/arterest/common/jwt/service/JwtServiceTest.java
  src/test/java/com/devtraces/arterest/service/auth/OauthServiceTest.java
  src/test/java/com/devtraces/arterest/service/like/LikeServiceTest.java
  src/test/java/com/devtraces/arterest/service/user/AuthServiceTest.java
Labels: ✨feature, 🔨refactor

#117 알림 삭제 API 구현
  src/main/java/com/devtraces/arterest/common/exception/BaseException.java
  src/main/java/com/devtraces/arterest/common/exception/ErrorCode.java
  src/main/java/com/devtraces/arterest/controller/notice/NoticeController.java
  src/main/java/com/devtraces/arterest/service/follow/FollowService.java
  src/main/java/com/devtraces/arterest/service/like/LikeService.java
  src/main/java/com/devtraces/arterest/service/notice/NoticeService.java
  src/main/java/com/devtraces/arterest/service/reply/ReplyService.java
  src/main/java/com/devtraces/arterest/service/rereply/RereplyService.java
  src/test/java/com/devtraces/arterest/service/notice/NoticeServiceTest.java
Labels: ☑️test, ✨feature

#115 팔로우 추천 리스트 구현
  src/main/java/com/devtraces/arterest/common/constant/CommonConstant.java
  src/main/java/com/devtraces/arterest/configuration/SchedulerConfiguration.java
  src/main/java/com/devtraces/arterest/controller/follow/FollowController.java
  src/main/java/com/devtraces/arterest/model/follow/FollowRepository.java
  src/main/java/com/devtraces/arterest/model/followcache/FollowRecommendationCacheRepository.java
  src/main/java/com/devtraces/arterest/model/followcache/FollowSamplePoolCacheRepository.java
  src/main/java/com/devtraces/arterest/model/recommendation/FollowRecommendation.java
  src/main/java/com/devtraces/arterest/model/recommendation/FollowRecommendationRepository.java
  src/main/java/com/devtraces/arterest/service/follow/FollowService.java
  src/test/http/test.http
  src/test/java/com/devtraces/arterest/service/follow/FollowServiceTest.java
Labels: ✨feature

#125 카카오 소셜 로그인 코드 수정
  src/main/java/com/devtraces/arterest/model/user/UserRepository.java
  src/main/java/com/devtraces/arterest/service/auth/OauthService.java
  src/test/java/com/devtraces/arterest/service/auth/OauthServiceTest.java
Labels: 🐞bugFix

#120 회원탈퇴 API 구현
  src/main/java/com/devtraces/arterest/controller/auth/AuthController.java
  src/main/java/com/devtraces/arterest/controller/auth/dto/request/DeleteUserRequest.java
  src/main/java/com/devtraces/arterest/model/follow/FollowRepository.java
  src/main/java/com/devtraces/arterest/model/notice/NoticeRepository.java
  src/main/java/com/devtraces/arterest/service/auth/AuthService.java
  src/test/java/com/devtraces/arterest/service/user/AuthServiceTest.java
Labels: ☑️test, ✨feature

#126 공란으로 이름 및 닉네임 검색시 빈배열 리턴
  src/main/java/com/devtraces/arterest/service/search/SearchService.java
Labels: 🐞bugFix

#119 특정 게시물에 좋아요 누른 유저 리스트 API 리팩토링
  src/main/java/com/devtraces/arterest/controller/follow/dto/response/FollowResponse.java
  src/main/java/com/devtraces/arterest/controller/like/LikeController.java
  src/main/java/com/devtraces/arterest/controller/like/dto/response/LikeResponse.java
  src/main/java/com/devtraces/arterest/service/like/LikeService.java
  src/test/java/com/devtraces/arterest/service/like/LikeServiceTest.java
Labels: ✨feature, 🔨refactor

#130 LikeResponse 오타 수정
  src/main/java/com/devtraces/arterest/controller/like/dto/response/LikeResponse.java
Labels: ✨feature
